
# This pipeline will print the secret superSecretVariable value from secret section.

trigger: none

pool: kubernetes-self-hosted-agent

# Use a secure variable
variables:
  secretVariable: $(superSecretVariable)

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: echo $(secretVariable)
      displayName: "Secret Value"
