
# This pipeline will print the PWD, and HOME values from environment variables.

trigger: none

pool: kubernetes-self-hosted-agent

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: |
          echo "Current working directory: $PWD"
          echo "User home directory: $HOME"
      displayName: "Env variable"
