
# This pipeline will execute the both the scripts based on the value of myVariable value.

trigger: none

pool: kubernetes-self-hosted-agent

# Define a user-defined variable
variables:
  myVariable: false

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: echo "This step will only run if myVariable is set to true"
      condition: eq(variables['myVariable'], 'true')
      displayName: "Conditional variable"
    - script: echo "This step will only run if myVariable is set to false"
      condition: eq(variables['myVariable'], 'false')
      displayName: "Conditional variable"
