
# This pipeline will print the templateVariable value from the template of myVariableTemplate.yaml file.

trigger: none

pool: kubernetes-self-hosted-agent

# Reference a variable template
variables:
- template: myVariableTemplate.yaml

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: echo $(templateVariable)
      displayName: "Variable template"
 