trigger: none

pool: kubernetes-self-hosted-agent

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: echo "Building on branch $(Build.SourceBranch)"
      displayName: "Pre Defined"
