trigger:
- main

pool: kubernetes-self-hosted-agent

# Define a user-defined variable
variables:
  customVariable: "Hello from user-defined variable"

# Define stages
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: echo $(customVariable)
